services:
  - type: worker
    name: naksir-telegram-bot
    env: python
    repo: https://github.com/your-username/naksir-telegram-bot
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    build:
      pythonVersion: 3.11.8
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TODAY_API_URL
        value: https://today-api-7f3i.onrender.com
